services:

  watchtower:
    image: containrrr/watchtower

    env_file: "${SERVICE_ROOT}/.env"

    environment:
      PUID: 1000
      GUID: 1000

    # ports:
    #   - 80:80

    ## Base homelab config
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock

    command: --cleanup --interval 500

    ## Base homelab config
    hostname: ${SERVICE_HOSTNAME}
    container_name: ${SERVICE_NAME}
    restart: unless-stopped

    networks:
      - default
      - ${HOMELAB_NETWORK}

networks:
  default:
   name: ${SERVICE_NETWORK}
  homelab_network_proxy:
   name: ${HOMELAB_NETWORK}
   external: true

