services:
  watchtower:
    image: nickfedor/watchtower

    env_file: "${SERVICE_ROOT}/.env"

    environment:
      PUID: 1000
      GUID: 1000
      TZ: Europe/Paris
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      WATCHTOWER_NOTIFICATION_URL: "discord://${DISCORD_TOKEN}@${DISCORD_CHANNEL}"
      WATCHTOWER_NOTIFICATION_TEMPLATE: |
        {{- if .Report -}}
          {{- with .Report -}}
        {{len .Scanned}} Scanned, {{len .Updated}} Updated, {{len .Failed}} Failed
              {{- range .Updated}}
        - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} updated to {{.LatestImageID.ShortID}}
              {{- end -}}
              {{- range .Fresh}}
        - {{.Name}} ({{.ImageName}}): {{.State}}
            {{- end -}}
            {{- range .Skipped}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
            {{- range .Failed}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
          {{- end -}}
        {{- else -}}
          {{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
        {{- end -}}

    # ports:
    #   - 80:80

    ## Base homelab config
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    ## Base homelab config
    hostname: ${SERVICE_HOSTNAME}
    container_name: ${SERVICE_NAME}
    restart: unless-stopped

    networks:
      - default
      - ${HOMELAB_NETWORK}

networks:
  default:
    name: ${SERVICE_NETWORK}
  homelab_network_proxy:
    name: ${HOMELAB_NETWORK}
    external: true
